import { Contract, Task, Escalation, TimelineEvent, DashboardStats, Receivables, TeamWorkload } from "./types";
import { dateOffset, todayStr } from "./utils";

export const sampleContracts: Contract[] = [
  {
    id: "LR-2024-0847",
    customerId: "CU-1201",
    customerName: "Ahmed Al-Rashid",
    customerPhone: "+971501234001",
    customerEmail: "ahmed.rashid@gmail.com",
    vehiclePlate: "DXB A 12345",
    vehicleModel: "Toyota Camry 2024",
    contractType: "daily",
    sourceCode: "DIRECT",
    startDate: dateOffset(-5),
    endDate: todayStr(),
    dailyRate: 150,
    totalAmount: 750,
    outstandingAmount: 150,
    salikCharges: 24,
    darbCharges: 0,
    fineCharges: 0,
    depositAmount: 1000,
    status: "active",
    tier: "tier1",
    assignedTo: "sree",
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: todayStr() + "T07:00:00",
    lastResponse: null,
  },
  {
    id: "LR-2024-0832",
    customerId: "CU-1198",
    customerName: "Sara Mohammed",
    customerPhone: "+971501234002",
    customerEmail: "sara.m@outlook.com",
    vehiclePlate: "DXB B 67890",
    vehicleModel: "Nissan Sunny 2023",
    contractType: "weekly",
    sourceCode: "DIRECT",
    startDate: dateOffset(-12),
    endDate: dateOffset(1),
    dailyRate: 120,
    totalAmount: 1680,
    outstandingAmount: 0,
    salikCharges: 12,
    darbCharges: 0,
    fineCharges: 0,
    depositAmount: 800,
    status: "active",
    tier: "tier2",
    assignedTo: "sree",
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: todayStr() + "T08:00:00",
    lastResponse: todayStr() + "T08:45:00",
  },
  {
    id: "LR-2024-0815",
    customerId: "CU-1185",
    customerName: "Khan Abdul Wahab",
    customerPhone: "+971501234003",
    customerEmail: "khan.wahab@yahoo.com",
    vehiclePlate: "DXB C 11111",
    vehicleModel: "Hyundai Accent 2023",
    contractType: "daily",
    sourceCode: "DIRECT",
    startDate: dateOffset(-8),
    endDate: dateOffset(-2),
    dailyRate: 100,
    totalAmount: 600,
    outstandingAmount: 200,
    salikCharges: 48,
    darbCharges: 0,
    fineCharges: 50,
    depositAmount: 500,
    status: "overdue",
    tier: "tier3",
    assignedTo: "sree",
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: todayStr() + "T09:00:00",
    lastResponse: null,
  },
  {
    id: "LR-2024-0789",
    customerId: "CU-1162",
    customerName: "Fatima Hassan Al-Maktoum",
    customerPhone: "+971501234004",
    customerEmail: "fatima.h@gmail.com",
    vehiclePlate: "DXB D 22222",
    vehicleModel: "Kia Picanto 2024",
    contractType: "monthly",
    sourceCode: "DIRECT",
    startDate: dateOffset(-35),
    endDate: dateOffset(-6),
    dailyRate: 80,
    totalAmount: 2400,
    outstandingAmount: 480,
    salikCharges: 96,
    darbCharges: 12,
    fineCharges: 0,
    depositAmount: 1500,
    status: "overdue",
    tier: "tier4",
    assignedTo: "fairoos",
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: todayStr() + "T09:00:00",
    lastResponse: null,
  },
  {
    id: "LR-2024-0801",
    customerId: "CU-1170",
    customerName: "Yango Driver — Ramesh",
    customerPhone: "+971501234005",
    customerEmail: "",
    vehiclePlate: "DXB E 33333",
    vehicleModel: "Toyota Yaris 2023",
    contractType: "monthly",
    sourceCode: "YANGO",
    startDate: dateOffset(-30),
    endDate: todayStr(),
    dailyRate: 70,
    totalAmount: 2100,
    outstandingAmount: 0,
    salikCharges: 0,
    darbCharges: 0,
    fineCharges: 0,
    depositAmount: 1000,
    status: "active",
    tier: "aggregator",
    assignedTo: null,
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: null,
    lastResponse: null,
  },
  {
    id: "LR-2024-0812",
    customerId: "CU-1180",
    customerName: "Careem Partner — Ali",
    customerPhone: "+971501234006",
    customerEmail: "",
    vehiclePlate: "DXB F 44444",
    vehicleModel: "Nissan Kicks 2024",
    contractType: "weekly",
    sourceCode: "CAREEM",
    startDate: dateOffset(-14),
    endDate: dateOffset(-3),
    dailyRate: 130,
    totalAmount: 1820,
    outstandingAmount: 390,
    salikCharges: 0,
    darbCharges: 0,
    fineCharges: 0,
    depositAmount: 1200,
    status: "overdue",
    tier: "aggregator",
    assignedTo: null,
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: null,
    lastResponse: null,
  },
  {
    id: "LR-2024-0851",
    customerId: "CU-1201",
    customerName: "Ahmed Al-Rashid",
    customerPhone: "+971501234001",
    customerEmail: "ahmed.rashid@gmail.com",
    vehiclePlate: "DXB G 55555",
    vehicleModel: "Mazda 3 2024",
    contractType: "weekly",
    sourceCode: "DIRECT",
    startDate: dateOffset(-10),
    endDate: dateOffset(2),
    dailyRate: 160,
    totalAmount: 1600,
    outstandingAmount: 0,
    salikCharges: 0,
    darbCharges: 0,
    fineCharges: 0,
    depositAmount: 1000,
    status: "active",
    tier: "tier2",
    assignedTo: "sree",
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: todayStr() + "T08:00:00",
    lastResponse: null,
  },
  {
    id: "LR-2024-0839",
    customerId: "CU-1195",
    customerName: "Omar Ali Ibrahim",
    customerPhone: "+971501234008",
    customerEmail: "omar.ali@hotmail.com",
    vehiclePlate: "DXB H 66666",
    vehicleModel: "Honda Civic 2024",
    contractType: "daily",
    sourceCode: "DIRECT",
    startDate: dateOffset(-3),
    endDate: dateOffset(-1),
    dailyRate: 200,
    totalAmount: 600,
    outstandingAmount: 200,
    salikCharges: 12,
    darbCharges: 0,
    fineCharges: 0,
    depositAmount: 1500,
    status: "overdue",
    tier: "tier3",
    assignedTo: "sree",
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: todayStr() + "T09:00:00",
    lastResponse: todayStr() + "T10:12:00",
  },
  {
    id: "LR-2024-0855",
    customerId: "CU-1208",
    customerName: "Maria Santos",
    customerPhone: "",
    customerEmail: "maria.s@gmail.com",
    vehiclePlate: "DXB I 77777",
    vehicleModel: "Chevrolet Spark 2023",
    contractType: "daily",
    sourceCode: "DIRECT",
    startDate: dateOffset(-2),
    endDate: todayStr(),
    dailyRate: 90,
    totalAmount: 180,
    outstandingAmount: 0,
    salikCharges: 0,
    darbCharges: 0,
    fineCharges: 0,
    depositAmount: 500,
    status: "active",
    tier: "tier1",
    assignedTo: "sree",
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: null,
    lastResponse: null,
  },
  {
    id: "LR-2024-0760",
    customerId: "CU-1140",
    customerName: "Rashid Al-Mansoori",
    customerPhone: "+971501234010",
    customerEmail: "rashid.m@legend.ae",
    vehiclePlate: "DXB J 88888",
    vehicleModel: "Toyota Corolla 2024",
    contractType: "monthly",
    sourceCode: "DIRECT",
    startDate: dateOffset(-31),
    endDate: dateOffset(-1),
    dailyRate: 110,
    totalAmount: 3300,
    outstandingAmount: 0,
    salikCharges: 0,
    darbCharges: 0,
    fineCharges: 0,
    depositAmount: 2000,
    status: "closing",
    tier: "tier3",
    assignedTo: "ann",
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: todayStr() + "T09:15:00",
    lastResponse: todayStr() + "T09:22:00",
  },
  {
    id: "LR-2024-0743",
    customerId: "CU-1128",
    customerName: "Priya Sharma",
    customerPhone: "+971501234011",
    customerEmail: "priya.s@outlook.com",
    vehiclePlate: "DXB K 99999",
    vehicleModel: "Renault Duster 2023",
    contractType: "monthly",
    sourceCode: "DIRECT",
    startDate: dateOffset(-45),
    endDate: dateOffset(-8),
    dailyRate: 95,
    totalAmount: 2850,
    outstandingAmount: 760,
    salikCharges: 132,
    darbCharges: 0,
    fineCharges: 200,
    depositAmount: 1200,
    status: "overdue",
    tier: "tier4",
    assignedTo: "karar",
    manualOverride: true,
    overrideReason: "Dispute over Salik charges — Ann reviewing",
    overrideUntil: dateOffset(3),
    lastContacted: dateOffset(-2) + "T09:00:00",
    lastResponse: dateOffset(-2) + "T11:30:00",
  },
  {
    id: "LR-2024-0862",
    customerId: "CU-1215",
    customerName: "Wei Chen",
    customerPhone: "+971501234012",
    customerEmail: "wei.chen@gmail.com",
    vehiclePlate: "DXB L 10101",
    vehicleModel: "MG ZS 2024",
    contractType: "daily",
    sourceCode: "DIRECT",
    startDate: dateOffset(-1),
    endDate: dateOffset(0),
    dailyRate: 85,
    totalAmount: 85,
    outstandingAmount: 0,
    salikCharges: 0,
    darbCharges: 0,
    fineCharges: 0,
    depositAmount: 500,
    status: "extended",
    tier: "active",
    assignedTo: null,
    manualOverride: false,
    overrideReason: null,
    overrideUntil: null,
    lastContacted: todayStr() + "T07:15:00",
    lastResponse: todayStr() + "T07:20:00",
  },
];

export const sampleStats: DashboardStats = {
  expiringToday: 4,
  contacted: 9,
  responded: 5,
  extended: 3,
  returning: 1,
  overdue: 5,
  closed: 12,
  immobilised: 0,
  messagesSent: 14,
  totalContracts: 48,
};

export const sampleReceivables: Receivables = {
  totalAed: 2280,
  totalCount: 5,
  byDaysOverdue: { "0": 2, "1-3": 3, "4-7": 1, "8-14": 1, "15+": 0 },
  byOwner: [
    { name: "Sree", count: 3, total: 634 },
    { name: "Fairoos", count: 2, total: 978 },
    { name: "Karar", count: 1, total: 1092 },
    { name: "Ann", count: 1, total: 0 },
  ],
};

export const sampleTasks: Task[] = [
  { id: "T-001", contractId: "LR-2024-0815", customerId: "CU-1185", customerName: "Khan Abdul Wahab", assignedTo: "sree", taskType: "urgent_followup", description: "2hr no-response. Vehicle: Hyundai Accent (DXB C 11111). Call customer.", priority: "urgent", status: "open", dueDate: todayStr(), createdAt: todayStr() + "T11:00:00", completedAt: null },
  { id: "T-002", contractId: "LR-2024-0789", customerId: "CU-1162", customerName: "Fatima Hassan", assignedTo: "fairoos", taskType: "collection", description: "Payment failed 2x. Manual collection needed. AED 588.", priority: "urgent", status: "in_progress", dueDate: todayStr(), createdAt: todayStr() + "T09:30:00", completedAt: null },
  { id: "T-003", contractId: "LR-2024-0760", customerId: "CU-1140", customerName: "Rashid Al-Mansoori", assignedTo: "ann", taskType: "closure", description: "Close contract. Zero outstanding. Fast-track deposit refund.", priority: "normal", status: "open", dueDate: todayStr(), createdAt: todayStr() + "T09:25:00", completedAt: null },
  { id: "T-004", contractId: "LR-2024-0760", customerId: "CU-1140", customerName: "Rashid Al-Mansoori", assignedTo: "rachel", taskType: "refund", description: "Deposit refund AED 2,000. Clean closure.", priority: "normal", status: "open", dueDate: todayStr(), createdAt: todayStr() + "T09:25:00", completedAt: null },
  { id: "T-005", contractId: "LR-2024-0743", customerId: "CU-1128", customerName: "Priya Sharma", assignedTo: "ann", taskType: "dispute", description: "Salik charge dispute. Customer claims charges are not hers. Verify.", priority: "high", status: "in_progress", dueDate: todayStr(), createdAt: dateOffset(-1) + "T14:00:00", completedAt: null },
  { id: "T-006", contractId: "LR-2024-0789", customerId: "CU-1162", customerName: "Fatima Hassan", assignedTo: "ops", taskType: "immobilise_review", description: "Vehicle DXB D 22222 — 6 days overdue. Review for immobilisation.", priority: "urgent", status: "open", dueDate: todayStr(), createdAt: todayStr() + "T09:00:00", completedAt: null },
  { id: "T-007", contractId: null, customerId: null, assignedTo: "sree", taskType: "invalid_contact", description: "Maria Santos (DXB I 77777) — no phone number. Email only.", priority: "high", status: "open", dueDate: todayStr(), createdAt: todayStr() + "T07:05:00", completedAt: null },
  { id: "T-008", contractId: "LR-2024-0743", customerId: "CU-1128", customerName: "Priya Sharma", assignedTo: "karar", taskType: "recovery", description: "Post-closure recovery. AED 1,092 outstanding. Day 3 follow-up.", priority: "high", status: "open", dueDate: todayStr(), createdAt: dateOffset(-3) + "T10:00:00", completedAt: null },
];

export const sampleEscalations: Escalation[] = [
  { id: "E-001", contractId: "LR-2024-0815", customerId: "CU-1185", customerName: "Khan Abdul Wahab", customerPhone: "+971501234003", vehicle: "Hyundai Accent (DXB C 11111)", escalationType: "no_response_2hr", triggerTime: todayStr() + "T11:00:00", callOutcome: null, resolved: false },
  { id: "E-002", contractId: "LR-2024-0789", customerId: "CU-1162", customerName: "Fatima Hassan", customerPhone: "+971501234004", vehicle: "Kia Picanto (DXB D 22222)", escalationType: "no_response_4hr", triggerTime: todayStr() + "T13:00:00", callOutcome: "no_answer", resolved: false },
];

export const sampleTimeline: TimelineEvent[] = [
  { id: "TL-001", type: "message", direction: "outbound", channel: "whatsapp", template: "A", contractId: "LR-2024-0847", customerName: "Ahmed Al-Rashid", detail: "Template A sent — contract expiring today", actor: "system", time: todayStr() + "T07:00:12" },
  { id: "TL-002", type: "message", direction: "outbound", channel: "whatsapp", template: "B", contractId: "LR-2024-0832", customerName: "Sara Mohammed", detail: "Template B sent — weekly expiring in 1 day", actor: "system", time: todayStr() + "T08:00:05" },
  { id: "TL-003", type: "message", direction: "inbound", channel: "whatsapp", contractId: "LR-2024-0832", customerName: "Sara Mohammed", detail: "Customer replied: EXTEND", actor: "customer", time: todayStr() + "T08:45:00" },
  { id: "TL-004", type: "payment", contractId: "LR-2024-0832", customerName: "Sara Mohammed", detail: "Payment link sent — AED 882.00 (7 days extension)", actor: "system", time: todayStr() + "T08:45:30" },
  { id: "TL-005", type: "message", direction: "outbound", channel: "whatsapp", template: "C", contractId: "LR-2024-0815", customerName: "Khan Abdul Wahab", detail: "Template C sent — 2 days overdue, AED 298", actor: "system", time: todayStr() + "T09:00:02" },
  { id: "TL-006", type: "message", direction: "outbound", channel: "whatsapp", template: "D", contractId: "LR-2024-0789", customerName: "Fatima Hassan", detail: "Template D sent — FINAL NOTICE, 6 days overdue, AED 588", actor: "system", time: todayStr() + "T09:00:08" },
  { id: "TL-007", type: "event", contractId: "LR-2024-0789", detail: "Immobilise flag set — 6 days overdue", actor: "system", time: todayStr() + "T09:00:10" },
  { id: "TL-008", type: "event", contractId: "LR-2024-0801", detail: "Aggregator contract (YANGO) flagged for manual review", actor: "system", time: todayStr() + "T07:00:15" },
  { id: "TL-009", type: "message", direction: "inbound", channel: "whatsapp", contractId: "LR-2024-0839", customerName: "Omar Ali Ibrahim", detail: "Customer replied: I want to return the car", actor: "customer", time: todayStr() + "T10:12:00" },
  { id: "TL-010", type: "event", contractId: "LR-2024-0839", detail: "Return initiated — Ops and Ann notified", actor: "system", time: todayStr() + "T10:12:05" },
  { id: "TL-011", type: "call", contractId: "LR-2024-0815", customerName: "Khan Abdul Wahab", detail: "Callers.ai call initiated — no response after 2hrs", actor: "system", time: todayStr() + "T11:00:30" },
  { id: "TL-012", type: "message", direction: "inbound", channel: "whatsapp", contractId: "LR-2024-0760", customerName: "Rashid Al-Mansoori", detail: "Customer replied: RETURN", actor: "customer", time: todayStr() + "T09:22:00" },
  { id: "TL-013", type: "payment", contractId: "LR-2024-0862", customerName: "Wei Chen", detail: "Payment received — AED 89.25. Contract extended to " + dateOffset(1), actor: "system", time: todayStr() + "T07:25:00" },
  { id: "TL-014", type: "event", contractId: "LR-2024-0862", detail: "Extension confirmed — new end date " + dateOffset(1), actor: "system", time: todayStr() + "T07:25:05" },
];

export const sampleWorkload: TeamWorkload = {
  sree: { total: 3, urgent: 1, high: 1, normal: 1 },
  ann: { total: 2, urgent: 0, high: 1, normal: 1 },
  rachel: { total: 1, urgent: 0, high: 0, normal: 1 },
  fairoos: { total: 1, urgent: 1, high: 0, normal: 0 },
  karar: { total: 1, urgent: 0, high: 1, normal: 0 },
  ops: { total: 1, urgent: 1, high: 0, normal: 0 },
};
